### ISSUE TITLE
xray demo hangs when trying to exit with ctrl+c in kitty

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#1601]
Now that I've found a workaround for using kitty in my system I was testing the demo and found that if you try to exit it using ctrl+C it just hangs. Using `q` works. It does exit well in all the other terminals I tried regardless.

BTW... the xray demo lasts 101 seconds for me... watching a word trying to spin very slow for almost 2 minutes, and in the second demo it's like torture, lol

**Comment by dankamongmen** [comment]
i assume this was in kitty? you're running into #1416 almost certainly. it's queued for fix by 2.3.0.

**Comment by joseluis** [comment]
Ah ok, you can close this if you think it's duplicate, thanks

**Comment by dankamongmen** [comment]
Yeah, if it was kitty, interrupting a long escape sequence (like say the graphics in `xray`) will lock the terminal. As @kovidgoyal pointed out in that issue, you can use the terminal reset keypress (ctrl+shift+delete by default) to unlock it. We've got what looks like a good solution for this described in #1416, and I intend to put it into effect this week, maybe tonight. Closing as a duplicate; sorry for the annoyance.

**Comment by dankamongmen** [comment]
Duplicate of #1416.

**Comment by dankamongmen** [comment]
Also, 101 seconds?!?!! No wonder you called it interminable the other day =]. It's about 20s for me in kitty, and about 15s in xterm. 101s is completely unacceptable lol.

**Comment by dankamongmen** [comment]
> Also, 101 seconds?!?!! No wonder you called it interminable the other day =]. It's about 20s for me in kitty, and about 15s in xterm. 101s is completely unacceptable lol.

i think this calls for framedropping. i'll make a bug on it. thanks for bringing this to my attention.

**Comment by dankamongmen** [comment]
I just committed a fix for #1416, and this ought no longer happen (subject to the caveats mentioned in the last comment there). Let me know if you see this again, or any other possibly-related problems, thanks!

**Comment by joseluis** [comment]
It still happens to me in the thread-xray branch, not in the master branch. But in the master branch if I kill the xray demo early I get this on stdout:
```
 notcurses 2.2.8 by nick black et al on xterm-kitty
  58 rows (18px) 213 cols (9px) (193,03KiB) 48B crend 256 colors+RGB
  compiled with gcc-9.3.0, 16B little-endian cells
  terminfo from ncurses 6.2.20200212
  avformat 58.29.100 avutil 56.31.100 swscale 5.5.100
^[_Gi=27;ENODATA:Insufficient image data: 7482624 < 7485696^[\
```

strace:
```strace
stat("/home/myuser/build/graphics/kitty/20.1/lib/kitty/terminfo", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/home/myuser/.terminfo", {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
stat("/etc/terminfo", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/lib/terminfo", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/usr/share/terminfo", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
access("/home/myuser/build/graphics/kitty/20.1/lib/kitty/terminfo/x/xterm-kitty", R_OK) = 0
openat(AT_FDCWD, "/home/myuser/build/graphics/kitty/20.1/lib/kitty/terminfo/x/xterm-kitty", O_RDONLY) = 4
fstat(4, {st_mode=S_IFREG|0644, st_size=3255, ...}) = 0
read(4, "\32\1\25\0\34\0\17\0i\1\242\5xterm-kitty|KovIdTTY"..., 32768) = 3255
read(4, "", 28672)                      = 0
close(4)                                = 0
ioctl(3, TCGETS, {B38400 opost isig -icanon -echo ...}) = 0
ioctl(3, TCGETS, {B38400 opost isig -icanon -echo ...}) = 0
ioctl(3, TCGETS, {B38400 opost isig -icanon -echo ...}) = 0
ioctl(3, TCGETS, {B38400 opost isig -icanon -echo ...}) = 0
ioctl(3, TIOCGWINSZ, {ws_row=58, ws_col=213, ws_xpixel=1917, ws_ypixel=1044}) = 0
write(3, "\33[?1h", 5)                  = 5
ioctl(3, TIOCGWINSZ, {ws_row=58, ws_col=213, ws_xpixel=1917, ws_ypixel=1044}) = 0
fcntl(0, F_GETFL)                       = 0x2 (flags O_RDWR)
fcntl(0, F_SETFL, O_RDWR|O_NONBLOCK)    = 0
mmap(NULL, 200704, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f03890ef000
write(3, "\33[39;49m", 8)               = 8
write(3, "\33(B\33[m", 6)               = 6
write(3, "\33]104\7", 6)                = 6
write(3, "\33[?1002;1006l", 13)         = 13
write(3, "\33_Ga=d\33\\", 8)            = 8
write(3, "\33[?1h", 5)                  = 5
write(3, "\33[?25l", 6)                 = 6
fstat(1, {st_mode=S_IFCHR|0620, st_rdev=makedev(0x88, 0x219), ...}) = 0
write(1, "\33[38;5;50m\n", 11
)          = 11
futex(0x7f0393250b94, FUTEX_WAKE_PRIVATE, 2147483647) = 0
openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/gconv/gconv-modules.cache", O_RDONLY) = 4
fstat(4, {st_mode=S_IFREG|0644, st_size=27002, ...}) = 0
mmap(NULL, 27002, PROT_READ, MAP_SHARED, 4, 0) = 0x7f03933ca000
close(4)                                = 0
futex(0x7f03931d5634, FUTEX_WAKE_PRIVATE, 2147483647) = 0
write(1, " notcurses 2.2.8 by nick black e"..., 57 notcurses 2.2.8 by nick black et al on xterm-kitty
) = 57
write(1, "  58 rows (18px) 213 cols (9px) "..., 126  58 rows (18px) 213 cols (9px) (193,03KiB) 48B crend 256 colors+RGB
) = 126
write(1, "  compiled with gcc-9.3.0, 16B l"..., 51  compiled with gcc-9.3.0, 16B little-endian cells
) = 51
write(1, "  terminfo from ncurses 6.2.2020"..., 37  terminfo from ncurses 6.2.20200212
) = 37
write(1, "  avformat 58.29.100 avutil 56.3"..., 54  avformat 58.29.100 avutil 56.31.100 swscale 5.5.100
) = 54
ioctl(2, TCGETS, {B38400 opost isig -icanon -echo ...}) = 0
write(2, "\33[38;5;203m", 11)           = 11
write(2, "\33(B\33[m", 6)               = 6
write(3, "\33[?1049h", 8^[_Gi=15;ENODATA:Insufficient image data: 7348797 < 7485696^[\
```

**Comment by dankamongmen** [comment]
`dankamongmen/thread-xray` is generally not going to work until it's done; don't look for love there.

yeah i saw that weird output a few times. i'd like to get it cleaned up, but i'm not yet sure exactly why it's happening. i don't consider it a particularly big deal, but it's gross for sure. i consider being able to exit without locking up the terminal more important, though.

**Comment by kovidgoyal** [comment]
On Fri, Apr 30, 2021 at 03:04:01AM -0700, Nick Black wrote:
> yeah i saw that weird output a few times. i'd like to get it cleaned up, but i'm not yet sure exactly why it's happening. i don't consider it a particularly big deal, but it's gross for sure. i consider being able to exit without locking up the terminal more important, though.

It's the error message kitty returns when loading an image fails. If you
dont want it you should use the control key that tells kity to be quiet.
