### ISSUE TITLE
ncdirect_render_image is panicking with sufficiently large images

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#866]
For me It always seem to produce NCBLIT_8x1. Is the blitting system unfinished?

I haven't seen any issues or comments about it, except for the one in `rgba_blitter_low()` in file `blitset.h` (indirectly called by `ncdirect_render_image()`:

```c
static inline const struct blitset*                                                                                     
rgba_blitter_low(bool utf8, ncscale_e scale, bool maydegrade, ncblitter_e blitrec) {                                    
  const struct blitset* bset;                                                                                           
  if(blitrec != NCBLIT_DEFAULT){                                                                                        
    bset = lookup_blitset(utf8, blitrec, maydegrade);                                                                   
  }else{                                                                                                                
    bset = lookup_blitset(utf8, ncvisual_default_blitter(utf8, scale), maydegrade);                                     
  }                                                                                                                     
  if(bset && !bset->blit){ // FIXME remove this once all blitters are enabled                                           
    bset = NULL;                                                                                                        
  }                                                                                                                     
  return bset;                                                                                                          
}
```

**Comment by dankamongmen** [comment]
The blitting system ought work for `NCBLIT_1x1` (ASCII), `2x1` (Unicode half blocks), `4x1` (Unicode quadrant blocks), and `BRAILLE` (Unicode braille). `8x1` is only implemented for plots, as it doesn't make much sense for general visuals. I'm very surprised that you'd be getting 8x1 for ncvisuals; are you referring to those, or ncplot?

To verify that the ncvisual blitters are working on your setup, try e.g. `./blitters ../data/warmech.bmp`. This ought produce a WarMECH from Final Fantasy I in the four implemented visual blitters. If you only get ASCII (to which `8x1` currently maps in an ncvisual context), you've almost certainly got a non-UTF8 `LANG`. But I doubt you have that, so let me know.

**Comment by dankamongmen** [comment]
Another thing you can try out is `./notcurses-view ../data/warmech.bmp` (or any other image/video file). You can press '1', '2', '4', and '6' to switch between `1x1`, `2x1`, `4x1`, and `BRAILLE`. Try it with e.g. `fm6.wmv` and you can do it as the video plays.

**Comment by dankamongmen** [comment]
For good examples on how the blitters are used, consulting `src/view/view.cpp` ought be most informative. I'm pretty sure this stuff works pretty well -- I've used it to render OpenGL and NEStopia etc.

If you're in plot context, `8x1` is the choice for `NCBLIT_DEFAULT`. Maybe that's what you mean? The blitter is set in the `ncvisual_options` struct passed to `ncvisual_render()`.

**Comment by joseluis** [comment]
Ok, I'm gonna test your suggestions, for now here is my minimal example in rust:

```rust
use libnotcurses_sys as nc;

extern "C" {
    fn libc_stdout() -> *mut nc::_IO_FILE;
}

fn main() { unsafe {
    let ncd: *mut nc::ncdirect = nc::ncdirect_init(std::ptr::null(), libc_stdout());

    render_image(&mut *ncd, nc::ncblitter_e_NCBLIT_1x1);
    render_image(&mut *ncd, nc::ncblitter_e_NCBLIT_2x1);
    render_image(&mut *ncd, nc::ncblitter_e_NCBLIT_BRAILLE);

    nc::ncdirect_stop(ncd);
}}


fn render_image(ncd: &mut nc::ncdirect, blit: nc::ncblitter_e) {
    unsafe {
        if nc::ncdirect_render_image(ncd,
            std::ffi::CString::new("image-16.png").unwrap().as_ptr(),
            nc::ncalign_e_NCALIGN_LEFT,
            blit,
            nc::ncscale_e_NCSCALE_NONE,
        ) !=0 {
           panic!("ERR: ncdirect_render_image");
        }
    }
}
```
![imagen](https://user-images.githubusercontent.com/5832068/89710433-46ccee00-d983-11ea-8c8e-0c82ecfb4a25.png)

**Comment by dankamongmen** [comment]
You'll want to get output like the following: https://nick-black.com/images/issues-866-notcurses.mkv

**Comment by dankamongmen** [comment]
Yeah that definitely looks like `1x1`. `8x1` maps to that implementation (`tria_blit`), so I'm thinking that's why you thought it was `8x1`. If you run those tests above and they work properly, I've got to think you're setting `ncvisual_options->blitter` wierdly (0 maps to `NCBLIT_DEFAULT` and ought default to `NCBLIT_2x2` in ncvisual context).

**Comment by dankamongmen** [comment]
It's too early here :/. Please note two edits to my comments above: I've provided the correct URI for the video, and the Quadblitter is `NCBLIT_2x2`, not `NCBLIT_4x1`. Ugh, apologies.

**Comment by dankamongmen** [comment]
but yeah they're definitely implemented =] check out `quadrant_blit` in `src/lib/blit.c` for what i believe to be the state of the art in terminal graphics rendering.

**Comment by joseluis** [comment]
> Another thing you can try out is `./notcurses-view ../data/warmech.bmp` (or any other image/video file). You can press '1', '2', '4', and '6' to switch between `1x1`, `2x1`, `2x2`, and `BRAILLE`. Try it with e.g. `fm6.wmv` and you can do it as the video plays.

> You'll want to get output like the following: https://notcurses.com/issue-866-notcurses.mkv

Yes, I confirm this works well.

> If you run those tests above and they work properly, I've got to think you're setting ncvisual_options->blitter wierdly (0 maps to NCBLIT_DEFAULT and ought default to NCBLIT_2x2 in ncvisual context).

I'm not setting visual_options since I don't have where to pass it, nor I seem to have access to planes in direct mode ... How should I do it? Maybe it is only working for full-screen mode?

**Comment by dankamongmen** [comment]
> I'm not setting visual_options since I don't have where to pass it, nor I seem to have access to planes in direct mode ... How should I do it? Maybe it is only working for full-screen mode?

Some of this you probably already know, just putting it all down to be complete:

* blitters are not used in the basic make planes/write characters to planes/render planes cycle, so if you're looking for how they're used there, you shouldn't be
* blitters are only used for `ncvisual` and `ncplot*` objects, when these objects are rendered to a plane
  * the true backing store of an `ncvisual` is a flat array of 32-bit RGBA pixels
  * the true backing store of an `ncplot` is a time series data structure
* you can render the same `ncvisual` to different (or the same) planes with different blitters and scaling and other options, because...
  * `ncvisual`s are rendered to terminal graphics with `ncvisual_render()`, which accepts a
  * `ncvisual_option` struct:
```
auto ncvisual_render(notcurses* nc, ncvisual* ncv,
                     const struct ncvisual_options* vopts) -> ncplane*;
#define NCVISUAL_OPTION_NODEGRADE 0x0001ull // fail rather than degrade
#define NCVISUAL_OPTION_BLEND     0x0002ull // use CELL_ALPHA_BLEND with visual

struct ncvisual_options {
  // if no ncplane is provided, one will be created using the exact size
  // necessary to render the source with perfect fidelity (this might be
  // smaller or larger than the rendering area). if provided, style is
  // taken into account, relative to the provided ncplane.
  struct ncplane* n; 
  // the style is ignored if no ncplane is provided (it ought be NCSCALE_NONE
  // in this case). otherwise, the source is stretched/scaled relative to the
  // provided ncplane.
  ncscale_e scaling;
  // if an ncplane is provided, y and x specify where the visual will be
  // rendered on that plane. otherwise, they specify where the created ncplane
  // will be placed.
  int y, x;
  // the section of the visual that ought be rendered. for the entire visual,
  // pass an origin of 0, 0 and a size of 0, 0 (or the true height and width).
  // these numbers are all in terms of ncvisual pixels.
  int begy, begx; // origin of rendered section
  int leny, lenx; // size of rendered section
  // use NCBLIT_DEFAULT if you don't care, to use NCBLIT_2x2 (assuming
  // UTF8) or NCBLIT_1x1 (in an ASCII environment)
  ncblitter_e blitter; // glyph set to use (maps input to output cells)
  uint64_t flags; // bitmask over NCVISUAL_OPTION_*
};
```

each time you call `ncvisual_render()`, you supply a (possibly `NULL`) `struct ncvisual_options`. The `blitter` field here is used to select a blitter. Leaving it 0 will select `NCBLIT_DEFAULT`, which means "let the object decide how it ought best be blitted" (this means `2x2` for `ncvisual` and `8x1` for `ncplot`).

does that help make things clear?

**Comment by dankamongmen** [comment]
and BTW here's how `ncvisual` rendering works:

* `ncvisual` is created using e.g. `ncvisual_from_file()`
  * this preps an `ncvisual` with a reference to an unpacked RGBA buffer representing the source (original size)
* 1 or more times: 
  * an `ncvisual_options` struct is optionally prepared to control the rendering
    * `NULL` will be interpreted as an all-0s/-`NULL` `ncvisual_options`
  * `ncvisual_render` is called to convert the image into cell graphics
    * the blitter is looked up, and its geometry ascertained. `NCBLIT_AxB` means each cell will represent AxB source pixels *of the scaled image*
    * the image is scaled in memory, if necessary, according to the target `ncplane` and the scaling parameter `scaling`
      * if no target plane is provided, an appropriately-sized one is created
    * the blitter is invoked on this scaled image, writing a series of cell graphics to the target plane
* if the source has more than one image (i.e. video), call `ncvisual_decode()` to get the next one

**Comment by dankamongmen** [comment]
This loop in `src/poc/blitters.c` really says it all:

```
  struct ncplane* std = notcurses_stdplane(nc);
  // FIXME not all work yet; this subset does
  const int blitters[] = {
    NCBLIT_DEFAULT, // let the ncvisual pick
    NCBLIT_1x1,     // full block                █
    NCBLIT_2x1,     // full/(upper|left) blocks  ▄█
    // NCBLIT_1x1x4,   // shaded full blocks        ▓▒░█
    NCBLIT_2x2,     // quadrants                 ▗▐ ▖▄▟▌▙█
    // NCBLIT_4x1,     // four vert/horz levels     █▆▄▂ / ▎▌▊█
    NCBLIT_BRAILLE, // 4 rows, 2 cols (braille)  ⡀⡄⡆⡇⢀⣀⣄⣆⣇⢠⣠⣤⣦⣧⢰⣰⣴⣶⣷⢸⣸⣼⣾⣿
    // NCBLIT_8x1,     // eight vert/horz levels    █▇▆▅▄▃▂▁ / ▏▎▍▌▋▊▉█
   // NCBLIT_SIXEL,   // 6 rows, 1 col (RGB), spotty support among terminals
    -1,
  };
  for(const int* blitter = blitters ; *blitter >= 0 ; ++blitter){
    for(int scaling = NCSCALE_NONE ; scaling <= NCSCALE_STRETCH ; ++scaling){
      for(int i = 1 ; i < argc ; ++i){
        ncplane_erase(std);
        const char* fname = argv[i];
        nc_err_e err;
        struct ncvisual* ncv = ncvisual_from_file(fname, &err);
        if(ncv == NULL){
          goto err;
        }
        notcurses_render(nc);
        struct ncvisual_options vopts = {
          .n = std,
          .scaling = scaling,
          .blitter = *blitter,
        };
        if(!ncvisual_render(nc, ncv, &vopts)){
          ncvisual_destroy(ncv);
          goto err;
        }
        notcurses_render(nc);
        struct timespec ts = {
          .tv_sec = 0,
          .tv_nsec = 500000000,
        };
        clock_nanosleep(CLOCK_MONOTONIC, 0, &ts, NULL);
        ncvisual_destroy(ncv);
      }
    }
  }

```

**Comment by dankamongmen** [comment]
This is hopefully a bit clearer:

```
  nc_err_e err;
  struct ncvisual* ncv = ncvisual_from_file(fname, &err);
  if(ncv == NULL){
    goto err;
  }
  struct ncplane* std = notcurses_stdplane(nc);
  // FIXME not all work yet; this subset does
  const int blitters[] = {
    NCBLIT_DEFAULT, // let the ncvisual pick
    NCBLIT_1x1,     // full block                █
    NCBLIT_2x1,     // full/(upper|left) blocks  ▄█
    // NCBLIT_1x1x4,   // shaded full blocks        ▓▒░█
    NCBLIT_2x2,     // quadrants                 ▗▐ ▖▄▟▌▙█
    // NCBLIT_4x1,     // four vert/horz levels     █▆▄▂ / ▎▌▊█
    NCBLIT_BRAILLE, // 4 rows, 2 cols (braille)  ⡀⡄⡆⡇⢀⣀⣄⣆⣇⢠⣠⣤⣦⣧⢰⣰⣴⣶⣷⢸⣸⣼⣾⣿
    // NCBLIT_8x1,     // eight vert/horz levels    █▇▆▅▄▃▂▁ / ▏▎▍▌▋▊▉█
   // NCBLIT_SIXEL,   // 6 rows, 1 col (RGB), spotty support among terminals
    -1,
  };
  for(const int* blitter = blitters ; *blitter >= 0 ; ++blitter){
    for(int scaling = NCSCALE_NONE ; scaling <= NCSCALE_STRETCH ; ++scaling){
      for(int i = 1 ; i < argc ; ++i){
        ncplane_erase(std);
        const char* fname = argv[i];
        struct ncvisual_options vopts = {
          .n = std,
          .scaling = scaling,
          .blitter = *blitter,
        };
        if(!ncvisual_render(nc, ncv, &vopts)){
          goto err;
        }
        if(notcurses_render(nc)){
          goto err;
        }
        struct timespec ts = { .tv_sec = 0, .tv_nsec = 500000000, };
        clock_nanosleep(CLOCK_MONOTONIC, 0, &ts, NULL);
      }
    }
  }
  ncvisual_destroy(ncv);
```

**Comment by joseluis** [comment]
Ok thank you, this is going to be useful for when I get to wrap the nvcvisual struct.

> blitters are only used for ncvisual and ncplot* objects, when these objects are rendered to a plane

I believe this is the full chain of functions following the trace of the `blitter` parameter when calling `ncdirect_render_image()`. I don't think changing that parameter is making a difference. 

`direct.cpp`
```C
nc_err_e ncdirect_render_image(ncdirect* n, const char* file, ncalign_e align,
                               ncblitter_e blitter, ncscale_e scale){
/* .... */
  auto bset = rgba_blitter_low(n->utf8, scale, true, blitter);
/* ... */
}
```
`blitset.h`
```C
static inline const struct blitset*
rgba_blitter_low(bool utf8, ncscale_e scale, bool maydegrade, ncblitter_e blitrec) {
/* ... */
  if(blitrec != NCBLIT_DEFAULT){
    bset = lookup_blitset(utf8, blitrec, maydegrade);
  }else{
    bset = lookup_blitset(utf8, ncvisual_default_blitter(utf8, scale), maydegrade);
/* ... */
}


static inline const struct blitset*
lookup_blitset(unsigned utf8, ncblitter_e setid, bool may_degrade) {
  if(setid == NCBLIT_DEFAULT){
    setid = NCBLIT_2x1;
    may_degrade = true;
  }
  // the only viable blitter in ASCII is NCBLIT_1x1
  if(!utf8 && setid != NCBLIT_1x1){
    if(may_degrade){
      setid = NCBLIT_1x1;
    }else{
      return NULL;
    }
  }
  const struct blitset* bset = notcurses_blitters;
  while(bset->egcs){
    if(bset->geom == setid){
      return bset;
    }
    ++bset;
  }
  return NULL;
}
```

**Comment by dankamongmen** [comment]
Ahhh, I forget that you are working with `ncdirect`. Let me examine this. I know that `ncneofetch` is using `ncdirect` to render images:

```
static void*
display_thread(void* vmarshal){
  struct marshal* m = vmarshal;
  drawpalette(m->nc);
  if(m->dinfo){
    if(m->dinfo->logofile){
      if(ncdirect_render_image(m->nc, m->dinfo->logofile,
                               NCALIGN_CENTER, NCBLIT_2x2,
                               NCSCALE_SCALE) != NCERR_SUCCESS){
        return NULL;
      }
    }
  }
  return NULL;
}
```

![2020-08-08-104152_722x857_scrot](https://user-images.githubusercontent.com/143473/89713142-c8ad1f00-d963-11ea-8f57-1fe36bbe97cf.png)

and that is definitely 2x2, as can be seen via copy-and-paste:

`▐▌       ▙▙      ▟▛      ▞▌▌    ▌▌ ▐▛▙   ▟▐▛ ▌▌▐   ▐▐▌  ▌▌    ▀▄▄▀▟▐▐  ▌▌▌   ▌▌▌`

**Comment by dankamongmen** [comment]
BTW @joseluis i will be attending to all your raised issues at some point very soon, but am simply embroiled in #818 right now and must defeat it or hurl myself into a volcano

**Comment by joseluis** [comment]
@dankamongmen Sure, don't worry. I couldn't really ask for more responsiveness on your part, you're the fastest responding maintainer I've ever met, just do what you have to do.

**Comment by dankamongmen** [comment]
> @dankamongmen Sure, don't worry. I couldn't really ask for more responsiveness on your part, you're the fastest responding maintainer I've ever met, just do what you have to do.

thanks kindly; i can't tell you how happy it makes me to have someone competent looking at my poor neglected rust bindings (and taking a frank, fresh look over my APIs). i'm not sure if you've picked up on it elsewhere, but i retained API freedom across 1.x; with 2.0 i've promised to start handling backwards compat and living under the strict regime of Semantic Versioning. so if you have suggestions, throw 'em out -- once 2.0 drops (planned for Q42020), it's much less free a playground. https://www.youtube.com/watch?v=diYAc7gB-0A

**Comment by joseluis** [comment]
Sure will do.

BTW I just noticed the same code I used before now panics when calling ncdirect_render_image ... just FYI...

**Comment by dankamongmen** [comment]
Here's `ncneofetch` using 2x2 on the left side, and 1x1 on the right side. The only difference between these two binaries is the `blitter` argument to `ncdirect_render_image()`:

![2020-08-08-210511_1426x1434_scrot](https://user-images.githubusercontent.com/143473/89722714-e194ef00-d9ba-11ea-8b85-6693f4eff6f0.png)

With that said, `ncdirect_render_image()` was added pretty recently, and is not the most rigorous function within notcurses, so I'm assuming your report to be a valid bug. I'll look into this as soon as #818 is done.

**Comment by dankamongmen** [comment]
> Sure will do.
> 
> BTW I just noticed the same code I used before now panics when calling ncdirect_render_image ... just FYI...

This was resolved in #878, I'm 100% certain.

**Comment by joseluis** [comment]
> This was resolved in #878, I'm 100% certain.

Hmm.... It still fails, but I will investigate it further after I finish the migration of the notcurses-rs repo.

**Comment by dankamongmen** [comment]
I am now reproducing your oiriginal problem: running your script (with a local file named `image-16.png`) draws all three with the 1x1 blitter. This looks for all the world like an encoding problem (without full UTF-8, all blitters fall back to ASCII, 1x1). Looking into it.

**Comment by dankamongmen** [comment]
Yeah, i think that's it. Your script isn't setting the locale, and `ncdirect` doesn't do that for you (maybe it should).

**Comment by dankamongmen** [comment]
hrmmm, nope, adding a setlocale() doesn't seem to have solved things.

**Comment by dankamongmen** [comment]
Confirmed that we have the correct distinct numbers coming in from the Rust layer, and yet we're selecting 1x1 each time.

**Comment by dankamongmen** [comment]
```
BLITTER 1 UTF8: 0
[ █]
BLITTER 2 UTF8: 0
[ █]

```

we're not setting the locale correctly after all, or at least not picking it up in `n->utf8`.

**Comment by dankamongmen** [comment]
`ENCODING: ANSI_X3.4-1968`

yep

**Comment by dankamongmen** [comment]
ahhh, i put the setlocale in the wrong place. This works:

```
[grimes](0) $ cat src/main.rs 
use libnotcurses_sys as nc;

extern "C" {
    fn libc_stdout() -> *mut nc::_IO_FILE;
}

fn main() { unsafe {
    let _ = libc::setlocale(libc::LC_ALL, std::ffi::CString::new("").unwrap().as_ptr());
    let ncd: *mut nc::ncdirect = nc::ncdirect_init(std::ptr::null(), libc_stdout());

    render_image(&mut *ncd, nc::ncblitter_e_NCBLIT_2x1);
    render_image(&mut *ncd, nc::ncblitter_e_NCBLIT_2x2);

    nc::ncdirect_stop(ncd);
}}


fn render_image(ncd: &mut nc::ncdirect, blit: nc::ncblitter_e) {
    unsafe {
        if nc::ncdirect_render_image(ncd,
            std::ffi::CString::new("image-16.png").unwrap().as_ptr(),
            nc::ncalign_e_NCALIGN_LEFT,
            blit,
            nc::ncscale_e_NCSCALE_NONE,
        ) !=0 {
           panic!("ERR: ncdirect_render_image");
        }
    }
}
[grimes](0) $ 
```

output:

```
[grimes](0) $ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `target/debug/notcurses`
ENCODING: UTF-8
BLITTER 2 UTF8: 1
[ ▄█]
              ▄▀  ▀▀▀▀▀▀▀▄                  
            ▄▀ ▀▀▀▀▀▀▀▀ ▀▀                  
            ▀ ▀▀▀▀▀▀▀ ▀ ▀▄                  
              ▀▀▀▀▀  ▀▀ ▀                   
               ▀ ▀▀▀▀ ▀                     
               ▀▀ ▀▀▀▀▀▄                    
           ▄▄▄▄▄▀▀▀▀▀  ▀▀▀▄▄▄               
         ▄▀▀ ▀▀▀ ▀▀▀▀▀   ▀▀▀ ▀▀▄            
         ▀▀▀ ▀  ▀▀ ▀▀▀ ▀ ▀▀▀▀  ▀            
         ▀▀▀ ▀   ▀▀▀▀ ▀  ▀  ▀▀ ▀            
         ▀▀  ▀   ▀▀▀▀▀  ▀  ▀▀▀ ▀▀           
          ▀▀▀ ▀ ▀▀▀▀▀   ▀▀▀▀▀▀▀▀            
             ▀ ▀▀▀▀▀▀▀▀▀▀▀ ▀▀▀              
       ▀ ▄▄▀▀▀ ▀▀        ▀▀▄ ▄▀▀            
         ▀▀▀▀ ▀▀▀▀▀▀▀▀▀ ▀▀▀▀▀ ▀▀▄▄▄▄▀       
      ▄▀▀ ▀▀▀▀▀▀▀▀ ▀▀▀ ▀▀ ▀▀▀▀▀▀▀▀ ▀        
     ▀▀▀▀▀▀▀▀▀ ▀ ▀▀   ▀  ▀▀▀▀  ▀▀▀▀▀▄       
     ▀▀▀▀ ▀  ▀ ▀ ▀▀▀ ▀  ▀  ▀▀▀▀▀▀▀▀▀▀▀      
    ▄▀ ▀    ▀ ▀     ▀ ▀▀▀ ▀▀     ▀▀▀        
   ▀▀ ▀    ▀▀    ▀▀▀▀    ▀ ▀                
  ▀▀  ▀▀▀▀ ▀▀▀▀▀▀▀▀▀▀   ▀▀                  
 ▀▀▀▀▀▀▀▀▀▀▀▀ ▀▀▀▀▀▀▀ ▀                     
▀▀▀ ▀▀▀▀▀▀  ▀▀▀▀  ▀       ▀▀                
▀  ▀▀         ▀▀     ▀  ▀ ▀▀                
                ▀  ▀▀    ▀▀                 
                         ▀▀▄                
                  ▀   ▀ ▀ ▀                 
                  ▀▀▀▀▀▀▀ ▀                 
                 ▄▀▀▀▀ ▀  ▀                 
                ▄▀    ▀  ▀                  
                ▀    ▀                      
               ▄  ▀▀ ▀▀                     
               ▀▀▀▀ ▀▀▀▀                    
                ▀▀▀ ▀ ▀                     
          ▄ ▀ ▀▀▀▀▀▀▀▀ ▄                    
            ▀▀▀ ▀ ▀▀ ▀▀▀                    
          ▀  ▀ ▀▀▀ ▀▀▀▀                     
          ▄▀  ▀▀▀▄▀▀ ▀                      
         ▄  ▀▀▀▄▀▀▀ ▀▀                      
          ▀ ▀▀▀▀▀▀ ▀                        
                ▀▀▀▀                        
         ▀▀▀▀▀   ▀ ▀ ▀                      
                 ▀▀  ▀                      
                  ▀ ▀                       
                 ▄▀ ▀▀     ▄▄▄              
      ▄▄▄▄▄▄                       ▄▄▄▄▄▄   
   ▄                                       ▄
   ▀                                       ▀
BLITTER 4 UTF8: 1
[ ▗▐▖▄▟▌▙█]
   ▌▌▌▐    
   ▌▟▟▐    
   ▌▞▟▐    
   ▌▛▙     
   ▌▙▐     
    ▀▜     
   ▀▀▜▙    
  ▌▙▌▐▀▙   
  ▐▐▛▌▐▐   
  ▐▐▌▌▐▐   
  ▌▐▌▐▌▌   
  ▌▌▀▟▐▞   
   ▀▞▀▙▟   
  ▐▌▐▌▐▐   
  ▛▀▜▄▐▙▀  
 ▌▀▞▙▟▞▜▐  
 ▜▟▞▌▌▄▄▜  
 ▌▐▟▄▐▜▄▞▟ 
 ▐▞▛▌▐▐ ▄  
 ▐▌▐▛▐▌    
▌▌▞▛▄▐▌    
▌▛▛▛▙▌▐    
▟▀▟▙▙▐▌    
   ▌▐▐▐    
    ▌▟▐    
    ▌▌▌    
    ▌▙▚    
    ▌▄▄    
    ▌▜▌    
    ▐▌▐    
    ▐▐     
    ▌▐     
    ▌▐     
    ▌▐     
  ▌▀▌▞     
  ▌▌▙▌     
  ▌▐▀▌     
  ▌▌▌▐     
  ▌▐▌▐     
  ▌▌▌▐     
  ▌▌▐▐     
  ▌▐▌▐     
    ▌▐     
    ▌▐     
    ▐▐▙▜   
 ▛▄▟▞▀▀▙▙▀ 
 ▚▞▀▀▀▀▀▀▙▙
 ▞▀▀▀▀▀▀▀▛▛
[grimes](0) $ 
```

**Comment by dankamongmen** [comment]
I would recommend that in the Rust wrapper, you

(1) always call `setlocale` as the first thing you do, using `LC_ALL, ""` as arguments. document that users of your crate ought have `LANG` properly defined.
(2) pass the `NCOPTIONS_INHIBIT_SETLOCALE` once you're doing so

**Comment by dankamongmen** [comment]
I'm able to reproduce your

```
[grimes](0) $ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/notcurses`
thread 'main' panicked at 'ERR: ncdirect_render_image', src/main.rs:27:12
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[grimes](101) $ 
```

using `data/megaman2.bmp`. Other images I was testing with did not trigger this panic. This is with the 1.6.11 AUR release on Arch.


though...hrmmm....images i was using before are also causing this panic. so let me test again with head.

**Comment by dankamongmen** [comment]
OK, yeah, I'm still seeing it on tip of trunk. Reopening + renaming.

**Comment by dankamongmen** [comment]
`ncneofetch` still seems to run just fine, oddly enough.

**Comment by dankamongmen** [comment]
oh nevermind i had misnamed the file. it would probably be good to differentiate between the various failure cases of this file as returned via the poorly-thought-out-but-working-well-enough `nc_err_t`, if that's propagated out through ncdirect (if it's not, i should probably add it). once i copied `data/megaman2.bmp` to `image-16.png` properly, it worked fine.

![2020-08-12-091120_248x1057_scrot](https://user-images.githubusercontent.com/143473/90018995-cc9ab300-dc7b-11ea-94e8-ac48e211c7ab.png)

**Comment by joseluis** [comment]
Yeah, it works for me now (except what seems incorrect image rendering in the case of 1x1x4 & 4x1 blit, which only renders the top half?)

In my case the panic was due to not finding the image, because it interprets the path relative to the directory you are calling the program from... oh well...

**Comment by joseluis** [comment]
> (1) always call `setlocale` as the first thing you do, using `LC_ALL, ""` as arguments. document that users of your crate ought have `LANG` properly defined.
> (2) pass the `NCOPTIONS_INHIBIT_SETLOCALE` once you're doing so

interestingly I don't see any difference by not doing those things, but I take note

**Comment by dankamongmen** [comment]
> Yeah, it works for me now (except what seems incorrect image rendering in the case of 1x1x4 & 4x1 blit, which only renders the top half?)

yeah those are exploratory/unimplemented. they both ought be falling back to 1x1 with a top half, exactly as you see. i intend to fill them in, but haven't been able to come up with a case where they're actually useful, so ehhhh they might just get disabled, we'll see.

**Comment by dankamongmen** [comment]
> > (1) always call `setlocale` as the first thing you do, using `LC_ALL, ""` as arguments. document that users of your crate ought have `LANG` properly defined.
> > (2) pass the `NCOPTIONS_INHIBIT_SETLOCALE` once you're doing so
> 
> interestingly I don't see any difference by not doing those things, but I take note

well without the setlocale(), you're not going to get upwards of 1x1, the ASCII blitter (it's just spaces and a background color). without setlocale(), you're stuck without any Unicode.

the latter is indeed not necessary. it just tells `notcurses_init()` "yes, i know i'm supposed to take care of setlocale(), and i have done so, do not try to". otherwise, `notcurses_init()` will attempt to setlocale() if it detects that it's been started in ASCII mode. this should not be a problem, but i don't know how every program intends to use POSIX locales, so i leave this escape hatch. i'm sorry if that doesn't make a terrible amount of sense.

**Comment by joseluis** [comment]
Ok... now I understand what it's doing, thanks for the explanation!

I've finished a simple [`direct-image` example](https://github.com/dankamongmen/notcurses-rs/blob/master/examples/direct-image.rs) in the new repo if you want to try it, as an example of the clean ergonomics I'm aiming for.

I think we can finally leave this issue.
